{% set name = "handy-archives" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/domdfcoding/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 953f262107acbc262cf666bac81d2b224cfc2233a96f55dbd1a14f7cac27d15d

build:
  number: 1
  # noarch is used. python issue on osx-64:
  # - https://github.com/python/cpython/issues/91310
  # - https://github.com/python/cpython/issues/90849
  # Workaround with ARCHFLAGS="-arch x86_64" not worked
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  #[py<36]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
    - flit-core >=3.2,<4
  run:
    - python >=3.9
  run_constrained:
    - python !=3.6.0

# FileNotFoundError: [Errno 2] No such file or directory: 'testtar.tar'
{% set ignore_tests = " --ignore=tests/test_tarfile.py" %}
# FileNotFoundError: [Errno 2] No such file or directory: 'zipdir.zip'
{% set ignore_tests = ignore_tests + " --ignore=tests/test_zipfile.py" %}

test:
  source_files:
    - tests
  imports:
    - handy_archives
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v {{ ignore_tests }} tests
  requires:
    - pip
    - pytest >=6.0.0
    - coincidence >=0.2.0

about:
  home: https://github.com/domdfcoding/handy-archives
  summary: Some handy archive helpers for Python.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Some handy archive helpers for Python.
  doc_url: https://handy-archives.readthedocs.io
  dev_url: https://github.com/domdfcoding/handy-archives

extra:
  recipe-maintainers:
    - domdfcoding
